apiVersion: v1
kind: Pod
metadata:
  name: edgeflow-dev
  namespace: edgeflow-test
  labels:
    app: edgeflow-dev
spec:
  nodeSelector:
    role: infra-core
  volumes:
    - name: udev
      hostPath: {path: /run/udev}
    - name: vchiq
      hostPath: {path: /dev/vchiq}
    - name: vcsm
      hostPath: {path: /dev/vcsm}
    - name: dma-heap
      hostPath: {path: /dev/dma_heap}
  containers:
    - name: dev
      image: yoonjaeko/evc-producer:12 
      envFrom:
        - configMapRef:
            name: edgeflow-config
      command: ["sleep", "infinity"] 
      securityContext:
        privileged: true
      volumeMounts:
        - name: udev
          mountPath: /run/udev
          readOnly: true
        - name: vchiq
          mountPath: /dev/vchiq
        - name: vcsm
          mountPath: /dev/vcsm
        - name: dma-heap
          mountPath: /dev/dma_heap
      env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: GATEWAY_HOST
          value: "localhost" 
---
apiVersion: v1
kind: Service
metadata:
  name: edgeflow-gateway-service
  namespace: edgeflow-test
spec:
  type: NodePort
  selector:
    app: edgeflow-dev 
  ports:
    - name: http-gateway
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000